### ISSUE TITLE
Does it take prompts?

### ISSUE THREAD

**Issue by husnoo** [YavorGIvanov/sam.cpp#23]
I couldn't see any code referring to prompting in the main.CPP.

**Comment by YavorGIvanov** [comment]
The only supported input prompt is points, which are determined by just clicking or hovering the chosen image. Additionally you can change the image by drag & drop. Do you mean mask prompts ?

**Comment by husnoo** [comment]
I had hoped that you could say "mask the dog" or something. But thanks
anyway!

**Comment by YavorGIvanov** [comment]
Yeah. Haven't implemented this still. Checkout https://github.com/IDEA-Research/Grounded-Segment-Anything?tab=readme-ov-file#open_book-step-by-step-notebook-demo for this functionality.
