### ISSUE TITLE
Does not start on Windows

### ISSUE THREAD

**Issue by kelteseth** [YavorGIvanov/sam.cpp#8]
Nothing happens except for the two prints. Also, what license does this project have? Cheers!
``` ps

# python 3.11
python -m pip install torch numpy
# downloaded sam_vit_b_01ec64.pth  and put it in checkpoints
python convert-pth-to-ggml.py checkpoints/sam_vit_b_01ec64.pth . 1
mkdir build && cd build 
# PS C:\vcpkg> .\vcpkg.exe install sdl2:x64-windows
cmake .. -DCMAKE_TOOLCHAIN_FILE="C:\vcpkg\scripts\buildsystems\vcpkg.cmake"
cmake --build . --config Release
# contains sam.exe and SDL2.dll
cd .\bin\Release\
 C:\Code\cpp\sam.cpp\build\bin\Release> .\sam.exe -t 16 -i ../../../img.jpg -m ../../../checkpoints/ggml-model-f16.bin
 
SDL_main: seed = 1693989358
SDL_main: loaded image '../../../img.jpg' (680 x 453)
PS C:\Code\cpp\sam.cpp\build\bin\Release>

```

**Comment by SpaceCowboy850** [comment]
Works for me.

You must get SDL2 **DEV** package for VC to work in Windows, then point CMAKE to where the sdl2-config.cmake resides.  After that everything worked for me.

cmake -DSDL2_DIR=E:\SDL2-devel-2.28.3-VC\SDL2-2.28.3\cmake ..

**Comment by spacewalk01** [comment]
I've integrated it to visual studio:
https://github.com/spacewalk01/sam-cpp-vs

**Comment by YavorGIvanov** [comment]
This was already added last week in the master branch
https://github.com/YavorGIvanov/sam.cpp/commit/39aa3ebbe35d5875e6a63f7b3cf60b61b6bd856b

**Comment by YavorGIvanov** [comment]
Closing for now. If any other similar problem happens on Windows, please open a new issue.
